[package]
name = "dv-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dv"
path = "src/main.rs"

[dependencies]
ctrlc.workspace = true
dv-core = { path = "../dv-core" }
quick-xml.workspace = true

[dev-dependencies]
serde_json.workspace = true

[build-dependencies]
serde_json.workspace = true

[lints]
workspace = true
