<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NuGetAudit>false</NuGetAudit>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
