<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NuGetAudit>false</NuGetAudit>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3">
      <IncludeAssets>compile;runtime</IncludeAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
      <NoWarn>NU1603;NU1701</NoWarn>
      <Aliases>JsonAlias</Aliases>
      <GeneratePathProperty>true</GeneratePathProperty>
    </PackageReference>
  </ItemGroup>
</Project>
