param(
  [string]$Commit = 'b0f34d51fccc69fd334253924abd8d6853fad7aa'
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $repositoryRoot 'crates/dv-core/src/legacy_pruning_data.rs'
$sourceRoot = "https://raw.githubusercontent.com/dotnet/dotnet/$Commit/src/sdk/src/Tasks/Microsoft.NET.Build.Tasks/FrameworkPackages"
$sourceNames = @(
  'netstandard2.0',
  'netstandard2.1',
  'netcoreapp2.0',
  'netcoreapp2.1',
  'netcoreapp2.2',
  'netcoreapp3.0',
  'netcoreapp3.1',
  'net5.0',
  'net6.0',
  'net7.0',
  'net8.0',
  'net9.0'
)

$sets = [ordered]@{}
$declarationPattern = [regex]::new(
  'internal static FrameworkPackages (?<property>\w+) \{ get; \} = new\((?<arguments>[^\r\n]+?)\)(?:\s*\{(?<body>.*?)^\s*\};|;)',
  [System.Text.RegularExpressions.RegexOptions]::Multiline -bor [System.Text.RegularExpressions.RegexOptions]::Singleline
)
$changePattern = [regex]::new('\{\s*"(?<id>[^"]+)"\s*,\s*(?:"(?<version>[^"]+)"|null)\s*\}')

foreach ($sourceName in $sourceNames) {
  $uri = "$sourceRoot/FrameworkPackages.$sourceName.cs"
  $content = (Invoke-WebRequest -UseBasicParsing $uri).Content
  $classMatch = [regex]::Match($content, 'internal static class (?<class>\w+)')
  if (-not $classMatch.Success) {
    throw "No FrameworkPackages class found in $uri"
  }
  $className = $classMatch.Groups['class'].Value
  foreach ($declaration in $declarationPattern.Matches($content)) {
    $propertyName = $declaration.Groups['property'].Value
    $arguments = $declaration.Groups['arguments'].Value.Split(',') | ForEach-Object { $_.Trim() }
    if ($arguments.Count -lt 2 -or $arguments.Count -gt 3) {
      throw "Unexpected FrameworkPackages constructor in $uri"
    }
    $frameworkToken = $arguments[0]
    if ($frameworkToken -match '^NetStandard(?<major>\d)(?<minor>\d)$') {
      $family = 'NetStandard'
    } elseif ($frameworkToken -match '^NetCoreApp(?<major>\d)(?<minor>\d)$') {
      $family = 'NetCoreApp'
    } elseif ($frameworkToken -match '^Net(?<major>\d)(?<minor>\d)$') {
      $family = 'NetCoreApp'
    } else {
      throw "Unexpected framework token $frameworkToken in $uri"
    }
    $frameworkName = switch ($arguments[1]) {
      'FrameworkNames.NetStandardLibrary' { 'Default' }
      'FrameworkNames.NetCoreApp' { 'Core' }
      'FrameworkNames.AspNetCoreApp' { 'AspNetCore' }
      'FrameworkNames.WindowsDesktopApp' { 'WindowsDesktop' }
      default { throw "Unexpected runtime framework $($arguments[1]) in $uri" }
    }
    $changes = [ordered]@{}
    $body = [regex]::Replace($declaration.Groups['body'].Value, '(?m)//.*$', '')
    $body = [regex]::Replace($body, '(?s)/\*.*?\*/', '')
    foreach ($change in $changePattern.Matches($body)) {
      $id = $change.Groups['id'].Value.ToLowerInvariant()
      $version = if ($change.Groups['version'].Success) { $change.Groups['version'].Value } else { $null }
      $changes[$id] = $version
    }
    $key = "$className.$propertyName"
    $sets[$key] = [pscustomobject]@{
      Key = $key
      Family = $family
      Major = [int]$Matches['major']
      Minor = [int]$Matches['minor']
      Framework = $frameworkName
      Base = if ($arguments.Count -eq 3) { $arguments[2] } else { $null }
      Changes = $changes
    }
  }
}

$effective = @{}
function Resolve-Set([string]$key) {
  if ($effective.ContainsKey($key)) {
    return $effective[$key]
  }
  if (-not $sets.Contains($key)) {
    throw "Unknown inherited FrameworkPackages set $key"
  }
  $definition = $sets[$key]
  $values = [ordered]@{}
  if ($definition.Base) {
    foreach ($entry in (Resolve-Set $definition.Base).GetEnumerator()) {
      $values[$entry.Key] = $entry.Value
    }
  }
  foreach ($entry in $definition.Changes.GetEnumerator()) {
    if ($null -eq $entry.Value) {
      $values.Remove($entry.Key)
    } else {
      $values[$entry.Key] = $entry.Value
    }
  }
  $effective[$key] = $values
  return $values
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('// @generated by tools/generate-legacy-pruning.ps1; do not edit.')
[void]$builder.AppendLine("// Source: dotnet/dotnet $Commit (the source revision shipped by SDK 10.0.100).")
[void]$builder.AppendLine('// Derived from the .NET SDK sources distributed under the MIT license.')
[void]$builder.AppendLine()
$setRows = [System.Collections.Generic.List[string]]::new()
$setIndex = 0
foreach ($definition in $sets.Values) {
  $values = Resolve-Set $definition.Key
  $constant = "PACKAGES_$setIndex"
  [void]$builder.AppendLine('#[rustfmt::skip]')
  [void]$builder.AppendLine("static ${constant}: &[LegacyPrunePackage] = &[")
  foreach ($id in ($values.Keys | Sort-Object)) {
    $parts = @($values[$id].Split('.') | ForEach-Object { [uint32]$_ })
    while ($parts.Count -lt 4) {
      $parts += 0
    }
    if ($parts.Count -ne 4) {
      throw "Unexpected package version $($values[$id]) for $id"
    }
    [void]$builder.AppendLine("  LegacyPrunePackage { id: `"$id`", numbers: [$($parts[0]), $($parts[1]), $($parts[2]), $($parts[3])] },")
  }
  [void]$builder.AppendLine('];')
  [void]$builder.AppendLine()
  $setRows.Add(
    "  LegacyPruneSet { family: LegacyTargetFamily::$($definition.Family), major: $($definition.Major), minor: $($definition.Minor), framework: PruningFramework::$($definition.Framework), packages: $constant },"
  )
  $setIndex++
}
[void]$builder.AppendLine('#[rustfmt::skip]')
[void]$builder.AppendLine('static LEGACY_PRUNE_SETS: &[LegacyPruneSet] = &[')
foreach ($row in $setRows) {
  [void]$builder.AppendLine($row)
}
[void]$builder.AppendLine('];')

[System.IO.File]::WriteAllText($outputPath, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $setIndex effective pruning tables at $outputPath"
